### ISSUE TITLE
Create Simple Agent

### ISSUE THREAD

**Issue by geowa4** [585-software/medera#9]
Make an Agent application to handle all messages from Slack. For now, this means our current response to "Hi" should be moved to the Agent. It should be assumed this Agent will run on a remote instance. The node running the Agent must connect to the Master node on boot.

**Comment by dantswain** [comment]
I'm trying to decide if this should be a separate project (as in `mix new medera_agent`).  I think it makes sense - the agent probably wants to keep a smallish footprint to live beside other applications.  The main problem I foresee is that we either end up with some duplicated code or a third project with shared code, which just makes organization more complicated.  An umbrella project might work, but in my experience umbrella projects are rough to work with.

**Comment by geowa4** [comment]
Want to try an umbrella project and see how it goes?

**Comment by dantswain** [comment]
Not really.  I've done them in the past and they never turned out to be the right solution.

**Comment by dantswain** [comment]
Closed by #20
